# Generated by Django 5.2.8 on 2025-11-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencyreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('responding', 'Responding'), ('resolved', 'Resolved')], default='pending', max_length=50),
        ),
    ]
