# Generated by Django 5.2.8 on 2025-11-08 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_emergencyreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='photo1',
            field=models.ImageField(blank=True, help_text='First verification photo (max 5MB)', max_length=255, null=True, upload_to='reports/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='photo2',
            field=models.ImageField(blank=True, help_text='Second verification photo (max 5MB)', max_length=255, null=True, upload_to='reports/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
