# Generated by Django 5.2.8 on 2025-11-08 14:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_emergencyreport_photo1_emergencyreport_photo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='photo1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='photo2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
